FAL_BILGISI_BULUNAMADI = "view_fortune_telling'da uygun fal bilgisi bulunamadi. Istek atan kullanici = {}"
GECERSIZ_ISTEK_YAPILDI = "view_any_zodiac'da uygun olmayan istek yapıildi."
HATA_MESAJI = "Gecersiz istek, islem."
FORM_YENILEME = "Form sayfasi yenilendi."
YENI_GIRDI_EKLENDI = "Yeni girdi veritabanina eklendi => {}"